server:
  port: 5051
  servlet:
    context-path: /srmoss
spring:
  profiles:
    active: @profileActive@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  #公共配置与profiles选择无关
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB